services:
  db:
    image: mysql:8.0
    container_name: umigo_db_prod
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: umigo_web_prod
    env_file:
      - .env.prod
    command: gunicorn umigo.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_prod:/app/media/
      - static_volume:/app/assets
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: umigo_nginx_prod
    ports:
      - "80:80"
    volumes:
      - media_prod:/app/media/
      - static_volume:/app/assets:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  mysql_data_prod:
  media_prod:
  static_volume: